version: '3.9'
 
services:

  mysql:
    container_name: "mysql"
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file: 
      - ./docker/dev/.env
    restart: always
    volumes: 
      - mysql_data:/var/lib/mysql

  redis:
    container_name: "redis"
    image: redis:alpine

  django:
    container_name: "django"
    build: 
      context: .
      dockerfile: ./docker/dev/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./docker/dev/.env
    restart: always
    depends_on: 
      - mysql
      - redis

  celery:
    container_name: "celery"
    restart: always
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    command: celery -A config worker -l INFO
    volumes: 
      - ./app:/usr/src/app
    env_file: 
      - ./docker/dev/.env
    depends_on: 
      - django

volumes: 
  mysql_data: